### ISSUE TITLE
Global Advancement Messages

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#11]

**Comment by chrissamael** [comment]
This is added in 1.0.12

**Comment by chrissamael** [comment]
Turns out speaking with Jeff and some other (probably custom advancements) triggers sent unknown advancement handles which result in the message stating the player in question received the advancement [null].

**Comment by DaMarine** [comment]
Yep, seems like it's all of our 'hidden' advancement triggers that don't have icons or toasts. Atm this is only used in The Tunnel, I assume exclusions in the same way we're going to be doing inclusions is the best solution for now.

**Comment by chrissamael** [comment]
Do you have a list of the advancements to which these 'hidden' triggers belong? We could hardcode-ignore them for the time being.
