### ISSUE TITLE
Wonky mob spawns in Archibald

### ISSUE THREAD

**Issue by DidsheMa** [DaMarine/Slabserver-Bugs#13]
Do you like zombie apocalypses? No? Well, then Archie probably isn't the place for you atm

**Describe the bug**
Large discrepancy in mob counts between main world and resource world

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Resource World
2. Wait until nighttime
3. Observe the significant number of mobs that will spawn in comparison to main world

**Expected behaviour**
Mob spawns should provide an indistinguishable experience to main world, with little to no wonkyness.

**Additional context**
Likely due to differing render distance, and per player spawns not being enabled.

**Comment by chrissamael** [comment]
Spawns on RW seem to have calmed down to a level comparable to Slabserver
