### ISSUE TITLE
Whitelisting requires ingame command

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#14]
**Describe the bug**
Whitelisting new players cannot be solely done through #applications channel, and requires /whitelist command to be run by staff from within the game

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to whitelist a new player
2. Player will be unable to join
3. Run `/whitelist` from ingame, using the new players IGN
4. Player will now be able to join the server.

**Expected behaviour**
Whitelisting can be completed fully from within #applications

**Additional context**
Issue being primarily tracked on admin board, will mirror updates here.

**Comment by Frogperson** [comment]
I've updated our application bot to support directly adding players to the whitelist database rather than relying on rcon. I believe this issue should be resolved now, but probably requires a bit more testing to confirm.
