### ISSUE TITLE
/tell commands censor swears

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#15]
**Describe the bug**
/tell, /w, or /r commands censor any fucking swearwords in the message

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to use `/tell DaMarine you're a piece of shit`
2. Message sent is `you're a piece of poopoo` which is nowhere near as eloquent

**Expected behaviour**
We should be able to fucking swear

**Comment by Frogperson** [comment]
Looks like VentureChat on the proxy server had a config file with options for chat filters as well. Since messaging is handled through bungee (to enable cross-server PMs) it was probably using this filter.

I've removed the filter, but the proxy server will need a restart to apply the change.

**Comment by DaMarine** [comment]
Still an issue after restarting proxy.

**Comment by DidsheMa** [comment]
Fixed by explicitly supplying the empty set [] in the filter regex section of all configs
