### ISSUE TITLE
Player respawns in end/nether in some cases

### ISSUE THREAD

**Issue by chrissamael** [DaMarine/Slabserver-Bugs#16]
*UPDATE*

**Describe the bug**
Player spawns in the wrong dimension upon death or end portal exit in the main world 

**To Reproduce**
1. Relog in nether or end the main world
2. [Enter the end and] Exit the end portal (or die) on the main world

**Expected behaviour**
Player respawns at the same coordinates, but in the overworld. 

**Additional context**
This was hard to pin down and fix, we were looking at the error in the gatekeeper code but it seemed to be caused by the innate respawn event intercepting at a higher level. This will make updating to 1.16 all the more interesting...

________________________________________________

**Describe the bug**
Under some circumstances a player's spawn is set to the ends or nethers world spawn.

**To Reproduce**
???

**Expected behaviour**
Player respawns at their bed, if this is an invalid spawn they get returned to (Slabserver) world spawn.

**Additional context**

**Comment by DaMarine** [comment]
[Addressed in 1.0.13](https://github.com/chrissamael/worldbordergatekeeper/releases/tag/1.0.13), fix uploaded for next restart

**Comment by DidsheMa** [comment]
Issue updated and addressed in Gatekeeper version 1.0.15

**Comment by chrissamael** [comment]
Haven't heard of a case of this happening since the update was released, so this can probably be closed.
