### ISSUE TITLE
Tunnel advancements get removed in Resource World

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#17]
**Describe the bug**
Any Tunnel advancements a player has will be removed upon entering the resource world

**To Reproduce**
Steps to reproduce the behaviour:
1. Have any Tunnel advancements awarded to you
2. Travel to Resource World
3. Note all Tunnel advancements are gone

**Expected behaviour**
Advancements should not be wiped

**Additional context**
Advancement folder just needs to be copied across

**Comment by GoldenDelicios** [comment]
fixed
