### ISSUE TITLE
playerlist shows only players online on Slabserver

### ISSUE THREAD

**Issue by chrissamael** [DaMarine/Slabserver-Bugs#18]
**Describe the bug**
Playerlist does not report players on both resource world and main

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter `playerlist` in #ingamechat
2. Receive the playerlist from slabbot
3. Note only the players online on slabserver show up

**Expected behaviour**
All players, no matter the server they are connected to (Resource World or Slabserver) should be listed.

**Additional context**
I guess this will be have to hooked up in some kind of way to the global tab list, unsure how/if as of yet.

**Comment by Frogperson** [comment]
If I can somehow grab a list of players from TAB (including their placeholders from AfkSleep) then it shouldn't be too hard to add them to the `playerlist` command. Unfortunately I had a quick look at the TAB source code and didn't see any API with this kind of info, so it might require a bit more digging and potentially putting that list together manually.

It honestly might just be easier to write a new plugin for this. Either that or we could continue waiting for DiscordSRV 2.0 with Bungee support to be released. Is this high enough priority that we want it done sooner? If so I can try to work on that this week.

**Comment by chrissamael** [comment]
I've spent a few hours thinking and checking stuff for this issue, haven't found anything easy to work with yet. Most likely we'll have to add this to the Gatekeeper (paper RW plugin) so that we can easily add the players on the RW when discordSRV starts building this list?

My idea is: adding a custom check if WorldborderGateKeeper is present, if so use that to get the playerlist from the RW (probably via PMS) and add this list to the existing ones respectively.

What do you think about this?

Now that we know the RW will be staying at least for the remainder of Season 3 we should get this sorted soon, but I'm unsure of the priority as of yet - looking through the other issues this doesn't seem less pressing than anything else, perhaps even the most pressing issue?

**Comment by Frogperson** [comment]
I haven't gotten a chance to look into TAB more yet, but from my initial poking, it doesn't appear that they have an easy list of players that we can grab.

Your idea to add a custom check into DiscordSRV is exactly the same as mine, except the additional functionality is added to Gatekeeper rather than a new plugin. I'm perfectly happy to have this added in for now, and we can readdress this once DiscordSRV 2.0 with Bungee support is released.

You still have my patch for DiscordSRV right?

**Comment by chrissamael** [comment]
Yeah I didn't find anything useful in that regard in TAB, either...

Yeah, DiscordSRV 2.0 was released btw, I'm using it on my testsetup with our custom slab patch, but I haven't yet seen any major changes that we can use for our case? Maybe I'm missing something here....

**Comment by Frogperson** [comment]
Unless I'm missing some exclusive beta or something, 2.0 has not been released yet, and still has no ETA. Are you referring to 1.20.1 maybe? That seems to be the most recent release.

**Comment by chrissamael** [comment]
I added this functionality to AFKSleep by forking it here: https://github.com/chrissamael/AfkSleep/tree/rw
I also changed up the discordSRV patch to accommodate for these changes: https://github.com/Slabserver/patches/blob/main/DiscordSRV.patch
I've also updated Discord to 1.20.1 during this process, which should with some additional configuring fix #28, too :)

**Comment by chrissamael** [comment]
Uploaded to the server, some more bugfixing later and we have a proper global playerlist functionality in #ingamechat :) During the addition of this I removed the "/100" part of the online player count, seeing as we now have 2 servers which, in theory, could host 200 players, which makes this a bit confusing to leave in, as I see it.
