### ISSUE TITLE
Player logging on to join the resource gets the wrong messages on discord

### ISSUE THREAD

**Issue by chrissamael** [DaMarine/Slabserver-Bugs#19]
**Describe the bug**
Any Tunnel advancements a player has will be removed upon entering the resource world

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Resource World
2. Relog
3. Note how you are mentioned as joining the server in #ingamechat, and right after leaving the server.

**Expected behaviour**
Only the join message should be displayed.

**Additional context**
This also happens when a player switches over from Slabserver to the Resource World, they get mentioned as leaving the server, or when logging out on the Resource World they don't get mentioned as leaving the server either.

**Comment by chrissamael** [comment]
My idea to tackle this one:

 - disable standard DiscordSRV join/leave messages
 - onPlayerNetworkJoin send PMS message to respective paper server
 - onPlayerJoinServer + PMS message trigger join/leave message forward to the discord,

This should cover most cases besides connecting to the RW while having no player online on the main world I think - in this case there wouldn't be a join/leave message, as there is currently no way to interact with discordSRV directly on the bungee.

**Comment by Frogperson** [comment]
I noticed DiscordSRV has an API, but unfortunately no join or quit message events https://github.com/DiscordSRV/DiscordSRV/tree/master/src/main/java/github/scarsz/discordsrv/api/events

I wonder if it would be possible to write a hook in DiscordSRV like some of these  https://github.com/DiscordSRV/DiscordSRV/tree/develop/src/main/java/github/scarsz/discordsrv/hooks/vanish  
Just something to watch Bungee for joins and disconnects and then block/send the join/leave messages as needed. We already have a custom DiscordSRV build so I don't mind adding a bit more to it.

Unfortunately without bungee being able to interface with DiscordSRV directly, I don't see any way to get around the empty slabserver issue which would prevent resource world messages from getting through. This is just an unfortunate limitation of the plugin messaging channel

**Comment by DidsheMa** [comment]
Fairly certain I can also solve this rather easily using the Bouncer and PMS after the network separation cleanup

**Comment by chrissamael** [comment]
I think this has been fixed with these updates in the [Gatekeeper](https://github.com/Slabserver/Gatekeeper/commit/f97427926cc5541cca7ba02f0233febfe00ddb10) and [Bouncer](https://github.com/Slabserver/bouncer/commit/fc200e9154a78c6e573eb8c5dece5511521e0a69)
