### ISSUE TITLE
dynmap displays message sent to the server via discord

### ISSUE THREAD

**Issue by chrissamael** [DaMarine/Slabserver-Bugs#21]
**Describe the bug**
[Dynmap](https://map.slabserver.org/index.html) shows chat messages in the lower left corner. Only messages sent by users on discord, to the minecraft server, are being displayed. No ingame messages from either server are displayed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to #ingamechat in our discord
2. Open the [dynmap](https://map.slabserver.org/index.html) 
3. Say hello
4. Compare dynmap chat and #ingamechat

**Expected behaviour**
Either no messages being displayed at all, or all messages (including those sent on venturechat)

**Comment by DaMarine** [comment]
Resolved! Messages no longer display, which is the expected behaviour as we do not have chat integration open on Dynmap, nor do we plan to :)
