### ISSUE TITLE
Advancement checks in functions are triggering null advancements in chat

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#22]

**Comment by DaMarine** [comment]
N.B: ensure the fix for this does not regress in 1.16 with the advancement name changes

**Comment by DaMarine** [comment]
Experienced again in 1.16 after getting `Ender Evolution`, and then killing the Shulker with a new account that got `Monster Hunter` for the first time.

**Comment by chrissamael** [comment]
I'm planning to rewrite the advancement handling to a) actively ignore recipes and b) scan Datapacks for advancements and auto-add them on loadup, should fix this issue for good

**Comment by DaMarine** [comment]
Testing Discord integration

**Comment by DaMarine** [comment]
Testing GitHub integration

**Comment by chrissamael** [comment]
The issue as such has been fixed by adding all advancements to the advancement map inside the plugin. As long as this list keeps getting updated with every added advancement we should be fine.
