### ISSUE TITLE
Players have chunk loading issues in both worlds

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#27]
**Describe the bug**
In the past few weeks, several players have found issues loading various chunks, particularly in the Nether. Staff suspect this may be related to potentially related to no-tick view distance, and/or villagers being ticked in these no-tick chunks

**Expected behaviour**
Players connection has no notable issues to their connection

**Comment by DidsheMa** [comment]
Has anyone ever heard anything else from this, especially since we've tried notick view with different configs on main now?

**Comment by chrissamael** [comment]
Only thing I've heard is people complaining about the connection to slab (main) being wonkier/slower, especially chunk loading seems to be a wider-spread issue now? Frequent relogging to solve the chunk loading issue is also apparent in #ingamechat

**Comment by GoldenDelicios** [comment]
Investigate if no-tick view distance is the cause of issues with chunk loading

**Comment by chrissamael** [comment]
Set the no-tick-view-distance to 8, effectively disabling it for now.

**Comment by DaMarine** [comment]
shruggie
