### ISSUE TITLE
/me doesn't show up in #ingamechat

### ISSUE THREAD

**Issue by marbou9** [DaMarine/Slabserver-Bugs#28]
**Describe the bug**
Messages using /me on the server doesn't show up in #ingamechat.

**Comment by Frogperson** [comment]
The way I fixed this previously was to just write a new /me plugin and make sure to send the text to Discord as well as in-game. I couldn't find any way to grab the text without doing that.

Should we just do that same "fix" again?

**Comment by chrissamael** [comment]
I'm working on using the recently added feature of DiscordSRV's "alerts" that catch a player using a command and then react to it by doing what was configured - usually sending a message to a channel, but the config params allow for more (embeds, from the top of my head, and something else I can't remember)

**Comment by DaMarine** [comment]
Losing the arm is a common issue and is indeed the result of markdown as you suggested, same can be seen here:  ¯\_(ツ)_/¯

One common way to get round it is tripling up on the arms, i.e. `¯\\\_(ツ)\_/¯`, which fixes it nicely: ¯\\\_(ツ)\_/¯. I'm trying this change in the `alerts.yml`.

**Comment by chrissamael** [comment]
I think my issue were the two _ , causing the face and brackets to be italic - do you have a comparably easy fix for this, too? :)

**Comment by GoldenDelicios** [comment]
in marine's example, the backslashes before the underscores escape them.

**Comment by chrissamael** [comment]
Smh, somehow I didn't see that, thanks for pointing out the obvious xD
I'll try this out, if it works I'd suggest updating discordSRV on live and enabling this :)

**Comment by DaMarine** [comment]
I checked with Frog and MC just to make sure we're in the clear in terms of the new required intents, just want confirmation of that and then I'm happy to update DiscordSRV :D

**Comment by chrissamael** [comment]
Updated DiscordSRV and enabled the alerts for /me to show up in #ingamechat, which it now does, as well as a borked version of shruggie (he's missing his left arm). As I don't know how to fix that easily I'd appreciate some input/help on this one looking forward, but I guess that could be done in a separate ticket :)

**Comment by DidsheMa** [comment]
Reopening this with same behaviour as before, /me and shruggie don't show up in #ingamechat although the DiscordSRV alerts seem to be enabled ¯\_(ツ)_/¯

**Comment by DidsheMa** [comment]
Turns out we didn't have generic /me forwarding enabled via discordSRVs alerts.yml; just the custom shruggie. Tried adding the former using what should be their newly updated syntax according to their wiki page/discord now - if generic /me forwarding works from next restart onward, the problem lies with our special shruggie condition

**Comment by chrissamael** [comment]
Generic /me forwarding works, but formatting is screwed:

`_Ya_BoiThom ¯(ツ)/¯`

**Comment by DidsheMa** [comment]
Closing because now #8 accurately reflects current behaviour, and that one is marked as a "won't fix" - if we wanna address armless shruggie further, I'd suggest reopening #8 
(I guess we can try and get the people on the discordsrv discord to help us with this)
