### ISSUE TITLE
Ender Evolution functionality does not work in the Resource World

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#29]
**Describe the bug**
As noted in the Resource World feedback, Ender Evolution does not work in the Resource World. This is likely a result of the 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter the Resource World
2. Try to throw a strength potion on a Shulkermite that is above Purpur in the End

**Expected behaviour**
Ender Evolution functionality/advancement works correctly, and is standardised between Main World and Resource World.

**Screenshots**
N/A

**Additional context**
Larger action here to better track our Slabserver datapack and make sure new changes are implemented in both the Resource World and Main world: https://github.com/Slabserver/Slabserver-Staff/issues/71

**Comment by GoldenDelicios** [comment]
Fixed more generally by resolving DaMarine/Slabserver-Staff#71
