### ISSUE TITLE
Name changes are not displayed in join messages

### ISSUE THREAD

**Issue by DidsheMa** [DaMarine/Slabserver-Bugs#31]
When a player changes their name, they should be displayed as "NEWNAME - formerly known as OLDNAME" for a certain amount of time. 
Slab SMP currently does not do this. 

Will look into it after the network separation and the resulting bouncer cleanup.

**Comment by DaMarine** [comment]
Working wonderfully in-game and in #ingamechat: https://discord.com/channels/146701388234227712/596920517643206656/796190353471832085, in line with vanilla behaviour too - thank you ❤️
