### ISSUE TITLE
Erroneous leave messages and delayed/double joins/leaves

### ISSUE THREAD

**Issue by DidsheMa** [DaMarine/Slabserver-Bugs#33]
1. Players entering the Bungee network but not entering the Paper server will in some cases (version mismatch, banned player) trigger an unintentional ingame leave message upon leaving the network. 

This should be an easy fix, just have the Bouncer keep track of who actually joined the server and not just the network.

2. Due to the nature of Plugin Messaging System, join/leave messages are now kept in memory and get dispensed in bulk if a world goes back online, and people joined/left the other while it was off. Noticeable during RW resets and server restarts. We also get a few double messages upon the latter - honestly not sure why.

There's two solutions to this:

- Short term: Add a timestamp to join/leave messages forwarded to the Paper gatekeeper plugin from the Bouncer, have the gatekeeper check for "decay" and only pass on relevant msgs

- Long term: Ditch PMS, and implement a simple SQL-based producer-consumer infrastructure for the join/leave message task within Bouncer and Gatekeeper. This would also allow us to circumvent the stupid requirement of needing at least one player to be online on the main world to be able to forward joins/leaves to Discord.

**Comment by chrissamael** [comment]
The "short term" solution is already present in the gatekeeper, it's being used for the advancement and death message forwarding from RW to main (and vice versa, for ingame display).

**Comment by DaMarine** [comment]
Working wonderfully in-game and in #ingamechat: https://discord.com/channels/146701388234227712/596920517643206656/796190353471832085, in line with vanilla behaviour too - thank you ❤️

**Comment by chrissamael** [comment]
Short term solution is currently live, working better overall but there still seem to be fringe (and sadly unreproduceable as of now) cases where leave announcements go missing - Didy and I noticed it happen three times yesterday, in a matter of hours to three different players.

**Comment by DidsheMa** [comment]
- Removed the fix for 1 again as it seems to be what ate up the leave messages

**Comment by DidsheMa** [comment]
Long term solution now implemented and tested in Bouncer/GK which should resolve this issue with all its components for good; pending deployment on Slab

**Comment by DaMarine** [comment]
Whole month without issues, 10/10 would leave/join/doublejoin the server again
