### ISSUE TITLE
Player respawn points get ignored on relog in certain cases

### ISSUE THREAD

**Issue by GoldenDelicios** [DaMarine/Slabserver-Bugs#36]
@DidsheMa commented on [Sun Apr 04 2021](https://github.com/DaMarine/Slabserver-Staff/issues/114)

> Hekkerman reported a bug to me that he has to set his spawn point every time he logs into the server.
> I tried to reproduce with my bed but to no luck, so I asked him to show me his bed, and could confirm it was happening there. It seems that the SpawnX/Z coords can be off when logging into the server; I assume from trying to restore their spawnpoint from the database, and if the offset puts your spawnpoint in a wall, your spawn point is obviously invalid. His bed is at 4623 63 -3014

Expected behaviour: relogging should in fact not delete players' spawnpoint and shove them to worldspawn

**Comment by chrissamael** [comment]
Tests seemed very promising (no issues at all) with [this](https://github.com/Slabserver/Gatekeeper/releases/tag/1.2.6) version, which is now also deployed on slab main, active with the next restart. I'll test this again on slab tomorrow, if we don't hear of any further issues with bed respawns we should be fine to close this ticket next meeting.
