### ISSUE TITLE
Double advancement messages

### ISSUE THREAD

**Issue by GoldenDelicios** [DaMarine/Slabserver-Bugs#38]
Advancements are sometimes announced twice in in-game chat.

**Comment by DidsheMa** [comment]
iceboxed until didy thesis

**Comment by chrissamael** [comment]
Advancements are currently transferred via the PMS, which has proven to be unreliable and annoying to work around anyways.

I suggest moving this over to use the same system we've been using for the join and leave messages - it's an additional thread running inside the gatekeeper plugins, checking the database every second for new messages to forward into ingamechat and discordSRV, if that's present.

I should be able to find some time in the next couple of days to tackle this and perhaps even ditch the PMS reliant code in its entirety.

**Comment by chrissamael** [comment]
Finally got around to doing so, https://github.com/Slabserver/Gatekeeper/releases/tag/v1.3.3 should fix this issue - moving this to review

**Comment by DidsheMa** [comment]
After watching ingamechat ingame for a while and asking people to confirm, Slab approves - thanks @chrissamael for the fix!
