### ISSUE TITLE
Double join messages after server restart

### ISSUE THREAD

**Issue by GoldenDelicios** [DaMarine/Slabserver-Bugs#39]
Players joining as soon as the server restarts may cause two join messages to appear, both in-game and in Discord. Examples:
https://discord.com/channels/146701388234227712/147017948912025601/848231718850789406
https://discord.com/channels/146701388234227712/596920517643206656/848229403304394803
https://discord.com/channels/146701388234227712/596920517643206656/846779847790690354

This seems to be caused by players trying to join the server just before it is ready to accept new connections.

![image.png](https://images.zenhubusercontent.com/5eb05dd296ceacae2580504c/7375a9a3-9014-4a7c-b9a8-677cf5f685fa)

May be related to #33.

**Comment by DidsheMa** [comment]
I'll look into this because bouncer is likely the most sensible level to address this, iceboxing until july 19th because thesis though since it's not exactly gamebreaking

**Comment by DidsheMa** [comment]
Found a small leftover threading inconsistency in the Bouncer that could potentially cause this, hopefully my change fixes it come next restart - might have to get back to this and investigate more thoroughly though

**Comment by GoldenDelicios** [comment]
This still happens:
https://discord.com/channels/146701388234227712/596920517643206656/913302467414999072

First "real" join (#console)
https://discord.com/channels/146701388234227712/596920414232510465/913302490747928606

Looking into this as well as #45

**Comment by chrissamael** [comment]
This is down to clients double joining at times - it's something we can't really avoid I think?

**Comment by GoldenDelicios** [comment]
The issue is caused by a user joining the server while it's still starting up. The second message is a second attempt by the user to join after being kicked.

There's an interesting behavior in which the server's player list does not yet contain the joining player in ServerConnectedEvent

**Comment by GoldenDelicios** [comment]
Two suggested solutions:
- Accompany the join message with a leave message when the connection fails, i.e. change [`Bouncer#onPlayerDisconnect`](https://github.com/Slabserver/bouncer/blob/master/src/main/java/didy/waterfallbouncer/Bouncer.java#L424) to use `ServerDisconnectEvent` instead of `PlayerDisconnectEvent`. 
  - From my observation, every ServerConnectedEvent is paired with a ServerDisconnectEvent, but not necessarily with a PlayerDisconnectEvent.
- Don't announce a join message unless the player has successfully connected to the Paper server, i.e. change [`Bouncer#smpJoin`](https://github.com/Slabserver/bouncer/blob/master/src/main/java/didy/waterfallbouncer/Bouncer.java#L393) to use `ServerSwitchEvent` and check if `event.getFrom() == null` (i.e. a not arriving from a previous server) instead of `ServerConnectedEvent`.
  - Despite the name, at the time ServerConnectedEvent is fired, the player is not yet part of that server's player list, this doesn't happen until ServerSwitchEvent is fired afterwards. This is also the event the TAB plugin uses to detect joins.

**Comment by DaMarine** [comment]
Chris has offered to look at this if he finds time - if that's not in the next month or two we'll just close this as a won't finish

**Comment by chrissamael** [comment]
Implemented the first suggestion and put it on the proxy - next restart should activate it

**Comment by chrissamael** [comment]
The first suggestion caused player disconnected and player connected messages on server switches between MW and RW

The second suggestion is not implementable without loosing the warning message that states: 
> As long as the main world is empty, Discord cannot be properly connected. Sorry. We will fix it later!

which tbf is a lie, seeing as we're not gonna fix it, but I think this message is more important than not having double join messages on a fringe case (as in, server restarts)

**Comment by DaMarine** [comment]
This is a rare and harmless enough issue we're not going to spend further time addressing this - closing!
