### ISSUE TITLE
Doing /away in creative server sends the message in wrong ingamechat channel

### ISSUE THREAD

**Issue by XeDotCom** [DaMarine/Slabserver-Bugs#44]
**Describe the bug**
If a person in the Creative server does `/away` to go afk, the message that should be sent to #creative-ingamechat is sent to #ingamechat

**To Reproduce**
Steps to reproduce the behaviour:
1. Join the Creative server
2. Do `/away [message]`
3. The message can be seen in #ingamechat and not #creative-ingamechat
**Expected behaviour**
The message should be sent to #creative-ingamechat

**Screenshots**
https://cdn.discordapp.com/attachments/596920517643206656/888683328293724210/unknown.png

**Additional context**
Players not on the Survival server but is on the Creative server can be seen doing /away in #Ingamechat which is weird

**Comment by chrissamael** [comment]
Slight config oversight, fixed!
