### ISSUE TITLE
The font for the stats page broke

### ISSUE THREAD

**Issue by XeDotCom** [DaMarine/Slabserver-Bugs#47]
**Describe the bug**
Instead of the Minecraft-y font that was used, a sans-serif font is being used as fallback.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://stats.slabserver.org'
2. See error

**Expected behaviour**
The Minecraft-y font should be rendered.
![image](https://user-images.githubusercontent.com/69308852/143431904-cd00646e-940a-4858-84f6-2e6c93c1ede4.png)

**Screenshots**

**Additional context**

**Comment by XeDotCom** [comment]
Chris fixed it

**Comment by chrissamael** [comment]
I don't think I fixed this, I fixed the http => https redirect :)

**Comment by chrissamael** [comment]
Now I've fixed it, I think - care to confirm it working on your end, too, @XeDotCom ? :)

**Comment by DaMarine** [comment]
Verified by Xe, closing ![proof](https://user-images.githubusercontent.com/10583568/143606014-df082459-2824-45bd-9ac1-c624f4849d4b.png)
