### ISSUE TITLE
DaMarine displays as white in game chat

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#5]
**Describe the bug**
When talking in chat from within the game, DUM shows up as white

**To Reproduce**
Steps to reproduce the behaviour:
1. As Da, type out a word or sentence and send the message

**Expected behaviour**
Name should show as green to reflect role colour displayed elsewhere

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5dddbc4d316e4c00011f6f72/1f4004fc-5def-4bb0-a2af-719103c31c60)

**Comment by chrissamael** [comment]
I'm not sure if this applies to all admins, or just DaMarine.

**Comment by joeydunn22** [comment]
Frog, MC, Nosrepgorf, and GoldenDelicios all showed green as of 6/15/2020

**Comment by DaMarine** [comment]
rip marine

**Comment by DaMarine** [comment]
Fixed, green is the new white, all is well in the world again.
