### ISSUE TITLE
Investigate RW blocklag

### ISSUE THREAD

**Issue by chrissamael** [DaMarine/Slabserver-Bugs#50]
> Alfman007:  the block lag in the RW is terrible, I'm trying to fill in a lava pool and every time I remove the blocks there is still some lava in it that comes out of no where

Investigate!

**Comment by DaMarine** [comment]
![B767086F-C4C6-4757-B803-61181EA7698D](https://user-images.githubusercontent.com/10583568/168185829-8549297f-7e2b-4f73-8ecb-01976262b3e9.jpeg)

tps and server cpu usage seem okay. Asked Alfman for details about their connection

**Comment by DaMarine** [comment]
This seemed to naturally resolve, nor do I know what we'd begin to action to try and address such an issue. Putting this down to short term disruption somewhere, and closing.
