### ISSUE TITLE
RW Bed Message Broken

### ISSUE THREAD

**Issue by AlfmanOO7** [DaMarine/Slabserver-Bugs#51]
### Server

Survival Server (RW)

### Describe the bug

The default respawn point set message "Respawn point set" is showing up in the RW when sleeping/attempting to set your spawn. (see 
![image](https://user-images.githubusercontent.com/62825044/177124552-6a085182-98d3-4b8a-8c33-073adf16c8fb.png)

### Expected behaviour

That the "You cannot set your spawn point in the resource world" message would show up (I have no screenshots of this message so this may not be the correct wording)

### Steps to reproduce

1. start Minecraft
2. log onto the server
3. go to the RW
4. place down a bed
5. right-click on the bed
6. read the incorrect respawn point set message in the chat

### Checklist

- [X] I have checked the Slabserver-Bugs repo to make sure this is not reported, or marked as "Won't Fix".

**Comment by GoldenDelicios** [comment]
Fixed by allowing spawn points to be set in the resource world
