### ISSUE TITLE
AFK messages are sent twice in #ingamechat

### ISSUE THREAD

**Issue by GoldenDelicios** [DaMarine/Slabserver-Bugs#57]
![image.png](https://images.zenhubusercontent.com/5eb05dd296ceacae2580504c/adcd5db3-e55e-41b8-9652-47736545559c)

**Comment by chrissamael** [comment]
Should be fixed in AFKSleep v2.3.4 which will be active on next restart

**Comment by chrissamael** [comment]
![image](https://user-images.githubusercontent.com/12401196/197367065-02ffaa19-4e8a-4bc0-8da6-e3cf4fc12e2b.png)
