### ISSUE TITLE
Advancements made in RW don't show in MW (and vice versa)

### ISSUE THREAD

**Issue by purpleKiiwi** [DaMarine/Slabserver-Bugs#58]
### Server

Survival

### Describe the bug

When a player makes an advancement in the resource world, a message appears for it in the discord #ingamechat but no message is visible in the main world. The same is true for MW->RW

### Expected behaviour

A chat message for an advancement made in the RW should also display in the MW
A chat message for an advancement made in the MW should also display in the RW

### Steps to reproduce

1. Player in the resource world makes an advancement
2. A different player in the main world observes that they see nothing 

### Additional info

![obrazek](https://user-images.githubusercontent.com/30413087/198737047-fc24a42a-b9fc-427e-87c5-06011e873481.png)
![obrazek](https://user-images.githubusercontent.com/30413087/198737121-ad0a3e1a-1cca-4565-9c7f-004398255e2a.png)

### Checklist

- [X] I have checked the Slabserver-Bugs repo to make sure this is not reported, or marked as "Won't Fix".

**Comment by chrissamael** [comment]
MC has fixed some code and I've uploaded it to slab, it will be activated once the server restarts and should fix this (and another, secondary, issue relating to system messages across the two servers)

Thanks for reporting it! Will keep this open until confirmed working :)

**Comment by chrissamael** [comment]
~~Confirmed not working, have to dive deeper in this~~

**Comment by DaMarine** [comment]
Pending validation the new fix has been uploaded to slab

**Comment by chrissamael** [comment]
I think this is still an open issue, even with the fix uploaded to slab

**Comment by GoldenDelicios** [comment]
Fixed and confirmed
