### ISSUE TITLE
Mounted players lose their mount when logging back in

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#6]
**Describe the bug**
Any player riding a mount, on either main or resource world, that disconnects from the server, will lose their mount when logging back in.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start riding a horse
2. Disconnect from either server
3. Reconnect to the server

**Expected behaviour**
You remain riding your mount upon returning to the world

**Comment by chrissamael** [comment]
This should be fixed in 1.0.11, was tested in development with:
 - horses
 - mules
 - donkeys
 - llamas
 - pigs
 - minecarts
 - boats
