### ISSUE TITLE
TAB health status incorrectly displayed on SMPNetwork

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#60]
### Server

Survival, Resource

### Describe the bug

In upgrading to its 1.19.4 version, the TAB plugin seems to have numerous inconsistencies or unexpected quirks compared to its intended behaviour:

- Players are displaying '0 Health' above their usernames when in close proximity:
- No hearts are visible on the Resource tab screen to represent player health, instead represented with a 0 once again:

Configs appear to be identical between Survival and Resource, making this issue even stranger.

### Expected behaviour

- Tab screen in Resource should mirror that of Survival.
- Health status should not display above players.

### Steps to reproduce

1. On Survival, observe the tab list working as intended
2. Transfer to Resource
3. Press tab and note the inconsistency with Survival
4. Find another player on either server and stand in close proximity to observe the 0 health status.

### Additional info

- '0 Health' above usernames when in close proximity:
![image](https://user-images.githubusercontent.com/10583568/232037141-4c6d6875-a991-497e-8295-5c2c06a9c976.png)
- Resource tab screen showing 0 number to represent player health, instead of heart visuals:
![image](https://user-images.githubusercontent.com/10583568/232036920-568065ce-ca94-4d61-9ade-de9a128a69b6.png)

### Checklist

- [X] I have checked the Slabserver-Bugs repo to make sure this is not reported, or marked as "Won't Fix".

**Comment by chrissamael** [comment]
Found the issues, in TAB's config.yml on proxy the following values had to be set accordingly:

```yml
yellow-number-in-tablist:
  enabled: true
  value: '%player_health%'             <=
```
```yml
belowname-objective:
  number: '%health%'
  text: Health
  enabled: false                      <=
```

After changing these to the above values and running `/btab reload` both the 0 Health below the player names as well as the inconsistencies between the servers seem to have been solved.
