### ISSUE TITLE
Investigate players being placed at 0,0 after a database timeout related crash

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#61]
Twist reports that ['sometimes it does this after a crash'](https://discord.com/channels/146701388234227712/596920517643206656/1155823156808908840) - I was randomly looking at the panel, wanting to check up on the bluemap rendering progress, when I noticed everything being very sluggish for a few minutes. The system caught itself again, but survival had to restart.

Shortly after this restart, Twists alt [starved to death](https://discord.com/channels/146701388234227712/596920517643206656/1155822649629478913), which caught my attention.

First glance at the logs gives me a database timeout, so that would  be the preferred way of getting the server to crash - as such, we can't really do this on the test setup on our dedi and must resort to a local testing setup in which we can temporarily block connection to the mysql server

**Comment by chrissamael** [comment]
May or may not be related to the fix rolled out in gatekeeper v1.5.5

**Comment by DaMarine** [comment]
To the best of our knowledge, this has been fixed in v1.5.5 and/or has not been reported again by anyone
