### ISSUE TITLE
Double advancement messages in discord

### ISSUE THREAD

**Issue by chrissamael** [DaMarine/Slabserver-Bugs#63]
![Image](https://github.com/Slabserver/Slabserver-Bugs/assets/12401196/4ed0203e-f8fc-4968-aa23-bb9014427da8)

happened [here](https://discord.com/channels/146701388234227712/596920517643206656/1188362145600110673)

Happens seemingly upon switching servers, have to investigate more

**Comment by DaMarine** [comment]
No observed cases of this since we moved it to review, closing!
