### ISSUE TITLE
Some shruggies are not escaped properly

### ISSUE THREAD

**Issue by DaMarine** [DaMarine/Slabserver-Bugs#8]
**Describe the bug**
Certain string characters will not get escaped properly between Discord and ingame

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to type the following characters `\/""` either ingame or on Discord
2. The message will not be sent between the two endpoints due to string formatting jank

**Expected behaviour**
Messages get sent correctly from either endpoint

**Comment by chrissamael** [comment]
Judging by the errorlogs coming up on resource, this is a VentureChat bug, probably in their connection to DiscordSRV

**Comment by DaMarine** [comment]
Discussing with Chris, he's sure that this should be a simple character escape either in VentureChat or DiscordSRV. Do either of you have any preference where we solve this one @Frogperson? Chris is very happy to help out with this as it seems pretty straightforward.

**Comment by chrissamael** [comment]
This should be re-tested after our update to 1.16.2

**Comment by DaMarine** [comment]
Still an issue as of today

**Comment by chrissamael** [comment]
Adding `message = message.replace("\"", "\\\"");` to VentureChat's handling of DiscordSRV messages seems to do the trick (in my local testings), I've [https://www.spigotmc.org/threads/venturechat.24005/page-417#post-3964494](contacted) Aust1n if this is the way to do it or if this fix should be placed somewhere else.

**Comment by chrissamael** [comment]
Issue was fixed by adding the above noted escape to the message in VentureChat, but I'm currently running into the issue of not being able to build VentureChat, iIrc. Overall it's quite the "jack of all trades" chat plugin, of which we're using, to my knowledge, only the global chat functionality? Perhaps we should reconsider our choice for chat plugin at some point down the line?

**Comment by DidsheMa** [comment]
Closed this accidentally, we still do have the issue of our custom venturechat patch for it not building on new versions. 
We'll try again, but I'd also advocate looking into whether we should actually stick with Venturechat, it's probably more payload than we need and has caused a headscratcher or two along the way

**Comment by GoldenDelicios** [comment]
Only issue remaining is /shruggies losing an arm when sent from Minecraft -> Discord

**Comment by DaMarine** [comment]
Alright, finally admitting defeat on this after several further attempts and discussions with chris, closing.

**Comment by DaMarine** [comment]
Didn't write "closing ¯\_(ツ)_/¯"...


oh well ¯\_(ツ)_/¯

**Comment by DidsheMa** [comment]
I've taken this up with the discordsrv support crew for one last campaign to give Shruggie his arms back and they seemed surprisingly keen to help; reopening. Let's see if their suggestion does it come next restart

**Comment by DidsheMa** [comment]
Not sure if we wanna bother with a discordsrv snapshot build just for Shruggie, but this should hopefully no longer be an issue with the next release, and Shruggie shall get all of his arms back! \o/
![Screenshot from 2021-09-13 12-24-38](https://user-images.githubusercontent.com/47526879/133068501-ff393b97-37f5-44b5-bab7-b3b6daf01bfc.png)

**Comment by DaMarine** [comment]
Picked this up again with the DiscordSRV staff 🤞

**Comment by DaMarine** [comment]
Thanks to MC for fixing this one - we now have a simple plugin that takes care of this, using the Player.chat method in bukkit to send a shruggie when the command is run.

This is sent as a completely normal chat messsage and transferred between both worlds as well as Discord. The bukkit alias and configured command in VentureChat are disabled as a result of this alternate fix.
